name: Procon-gardener

on:
  schedule:
  - cron: "0 */6 * * *"
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.17

    - name: Install procon-gardener
      run: |
        go install github.com/masa-oh/procon-gardener@latest
        procon-gardener init

    - name: Edit config.json
      run: |
        cd ../../../.procon-gardener
        jq '.atcoder.repository_path|="."' config.json > tmp
        mv tmp config.json
        jq '.atcoder.user_id|="${{ secrets.MY_ATCODER_ID }}"' config.json > tmp
        mv tmp config.json
        jq '.atcoder.user_email|="${{ secrets.MY_EMAIL_ADDRESS }}"' config.json > tmp
        mv tmp config.json

    - name: Archive
      run: procon-gardener archive

    - name: Git push
      run: git push
